Download images from doc asset endpoint
zetaalphavector/VOSviewer-Online pull request #22
Opened 2024-06-20 14:41 UTC by pavlosZakkas

2024-06-21 11:57 UTC, frejonb commented on src/api/api.js
> +  const response = await fetch(url, {
we need to make sure that we don't send the api token to any url, maybe look at the cluster titles part to see how it's handled there

2024-06-27 07:36 UTC, frejonb commented on src/pages/ZetaAlpha/utils.js
> +export const isAcceptableBackend = (url) => (url.includes("api-staging.") || url.includes("api.")) && (url.includes("zeta-alpha") || url.includes("zetaalpha"));
I think this is not enough, what if the url is `hacker.com/zeta-alpha`?

2024-06-27 07:49 UTC, frejonb commented on src/pages/ZetaAlpha/utils.js
> +export const isAcceptableBackend = (url) => (url.includes("api-staging.") || url.includes("api.")) && (url.includes("zeta-alpha") || url.includes("zetaalpha"));
actually we need to revisit if the other checks are correct in the sense that someone can't fake a url that leads to sending the token to a host that is not ours. I think getBaseUrl has this because it uses the origin of the sender and then makes the call to the same domain

2024-06-27 07:50 UTC, frejonb requested changes
one comment and let's make sure the security issue is really tight

2024-06-27 22:36 UTC, pavlosZakkas commented on src/pages/ZetaAlpha/utils.js
> +export const isAcceptableBackend = (url) => (url.includes("api-staging.") || url.includes("api.")) && (url.includes("zeta-alpha") || url.includes("zetaalpha"));
yes I also didn't like it, but not sure how to protect from that fully. Also, the `getBaseUrl` does not do any validation. It just creates a URL I think. The `isAcceptableUrl` is checking the origin to if there is some `search` text in the subdomain, which is also not strict.

If somebody loads a VOS with a custom url, the only way to validate it is to get the full domain and do an exact match, but how to make it work for all cases without having to add a url for every tenant?

So for the BE urls I think we have:
`https://api.zeta-alpha.com`, `https://api-staging.zeta-alpha.com`, `https://api.zetaalpha-poc.festo.net`, `https://api-staging-pr-XXX.zeta-alpha.com` and `http://localhost:3000/`.
I guess the most challenging is to match the tenants deployed on premise.

2024-06-28 18:08 UTC, frejonb commented on src/pages/ZetaAlpha/utils.js
> +export const isAcceptableBackend = (url) => (url.includes("api-staging.") || url.includes("api.")) && (url.includes("zeta-alpha") || url.includes("zetaalpha"));
the way `getBaseUrl` is used is that it takes the the url of the host and then creates the api version of it. You can see how it works in the example. It means that if the vos app lives in example.com, the api request will only be sent to api.example.com. This is safer because the token that was retrieved for example.com will be sent to api.example.com. In the current version of the images we are just listening to whatever the loaded json says. So if the app is hosted in example.com and the json loaded says to make a request to api.hacker.com then it will send the token from example.com over there.

2024-07-01 11:35 UTC, pavlosZakkas commented on src/pages/ZetaAlpha/utils.js
> +export const isAcceptableBackend = (url) => (url.includes("api-staging.") || url.includes("api.")) && (url.includes("zeta-alpha") || url.includes("zetaalpha"));
I decided to get the baseUrl of the origin and check if the given URL from the VOS json starts with the same base url. In principle, this should work for all cases, but I tested it only locally for now. If it looks okay I can test in the real VOS too.

2024-07-04 09:05 UTC, frejonb commented on src/components/ui/DynamicArticle/hooks/useResource.js
> +  }
this doesn't look correct in react. data and setData are handling the state of the component. You just renamed it but you need to use the same pattern. Meaning everything is setup to correctly expose the data (look where setData is used). The correct behavior is if you set this code after `const data = await attachmentApi(url, { signal });` and do `src = `data:${data.contentType};base64,${base64Content}` ?? undefined;`. Of course if you want to rename it to url you need to do it by replacing `const [data, setData] = useState(null);` with whatever names you want

2024-07-04 09:07 UTC, frejonb commented on src/components/ui/DynamicArticle/DynamicArticle.js
> +    imageContentUrl = image.includes('?') ? image.replace('?', '/content?') : `${image}/content`;
wasn't there a comment about this logic?

2024-07-04 09:17 UTC, pavlosZakkas commented on src/components/ui/DynamicArticle/DynamicArticle.js
> +    imageContentUrl = image.includes('?') ? image.replace('?', '/content?') : `${image}/content`;
I think no, but I can add one

2024-07-04 09:20 UTC, frejonb requested changes
last comments

2024-07-04 09:21 UTC, frejonb commented on src/components/ui/DynamicArticle/DynamicArticle.js
> +    imageContentUrl = image.includes('?') ? image.replace('?', '/content?') : `${image}/content`;
we said it was no accurate right? what if image is already`../content?`

2024-07-04 09:47 UTC, pavlosZakkas commented on src/components/ui/DynamicArticle/DynamicArticle.js
> +    imageContentUrl = image.includes('?') ? image.replace('?', '/content?') : `${image}/content`;
ah I thought you meant comment in code.

Hmm, if it already contains `/content` it will not enter the if so it will remain as is. Then, this URL will be called to get the resource content, right?

2024-07-10 09:40 UTC, frejonb approved these changes

2024-07-15 10:23 UTC, pavlosZakkas commented
I tested in prod after your approval, and there is an issue with the `origin` because the `origin` that VOSViewer "sees" is the origin of the iframe (ie `https://vos.zeta-alpha.com/`), which means that we cannot match the domain of the API request.
Instead, we need the origin of the parent frame.

The reason it is working for the clusters is because `postMessage` is used by the FE, and Vos viewer grabs the origin of the event (`ev.origin`) which is the origin of the parent.

Alternatives I checked is using `window.parent.location.origin` but this doesn't work for crossorigin iframe. Also I checked `document.referrer` which can work but it is not secure since it can be spoofed on the client side.
Did we have any similar issue again @frejonb ?

2024-07-15 16:57 UTC, frejonb commented
In Festo is it hosted also in vos.<their domain>? If so then I think it's ok. I thought the logic already worked like that, so vos.zeta-alpha.com maps to api.zeta-alpha.com. Another way is to grab the domain of the url that is passed to the vos app which is already api.zeta-alpha.com

2024-08-30 09:41 UTC, pavlosZakkas commented
tested in karlstad to verify that we can now see images in VOS.
Also tested in zetaalpha and regminer to verify nothing broke

2024-08-30 10:07 UTC, merged